services:
  postgres:
    image: postgres:16
    container_name: mcsa-postgres
    environment:
      POSTGRES_DB: modular_showcase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/postgres/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  mongo:
    image: mongo:7
    container_name: mcsa-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo/seed.js:/docker-entrypoint-initdb.d/seed.js:ro