spring.application.name=coreservices

server.port=8000

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/modular_showcase
spring.datasource.username=postgres
spring.datasource.password=admin123

spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.wjlq0bh.mongodb.net/component_showcase?appName=Cluster0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=componentshowcasesecretkey
app.jwt.secret=componentshowcasesecretkeycomponentshowcasesecretkey
app.jwt.expiration-ms=18000000