spring.application.name=coreservices

server.port=${PORT:8000}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:modular_showcase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://admin:admin123@cluster0.wjlq0bh.mongodb.net/component_showcase?appName=Cluster0}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=componentshowcasesecretkey
app.jwt.secret=componentshowcasesecretkeycomponentshowcasesecretkey
app.jwt.expiration-ms=18000000